# Generated by Django 4.0.3 on 2022-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
